.TH KECERAHAN 1 kecerahan
.SH NAME
kecerahan
.SH DESCRIPTION
kecerahan adalah sebuah program untuk mengontrol kecerahan layar dengan CLI.
.P
program ini hanya berjalan pada Linux, dan *BSD.
.SH USAGE
.TP
.B [sudo] kecerahan x
x = level kecerahan (1-999)
.SH BUGS
Send all bug reports to https://github.com/owodev/kecerahan
